name: CI workflow

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 1.8

      - name: Run KtLint
        run: ./gradlew lintKotlin

      - name: Run Detekt
        run: ./gradlew detekt
        
      - name: Assemble app
        uses: ./gradlew assembleDebug --stacktrace

      - name: Run unit tests
        uses: ./gradlew app:testDebugUnitTest basic-feature:testDebugUnitTest --stacktrace

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 24
          disable-animations: false
          script: ./gradlew connectedCheck --stacktrace
